#!/usr/bin/env python3
"""Validate artifacts generated by agent-voice.

The validator checks file shape, selected settings values, byte-for-byte
derivation, and exact ownership across files. Exact duplicate checks ignore
headings and fenced examples. They cannot detect semantic paraphrases; the
inventory, approval pass, and cold-reader probe own that judgment.
"""

import argparse
import json
import re
import sys
from pathlib import Path


BRACE_SLOT_RE = re.compile(r"\{\{[^{}\n]+\}\}")
HEADING_RE = re.compile(r"^#{1,6}(?:\s+|$)")
FENCE_OPEN_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
FENCE_CLOSE_RE = re.compile(r"^ {0,3}([`~]{3,})[ \t]*$")


class JsonArgumentParser(argparse.ArgumentParser):
    def error(self, message):
        print(json.dumps({"error": f"argument error: {message}", "status": "fail"}))
        raise SystemExit(2)


def read_text(path):
    try:
        return Path(path).read_bytes().decode("utf-8")
    except (OSError, UnicodeError) as exc:
        raise ValueError(f"cannot read UTF-8 text from {path}: {exc}") from exc


def logical_text(text, path):
    if text.startswith("\ufeff"):
        raise ValueError(f"UTF-8 BOM is not allowed: {path}")
    return text.replace("\r\n", "\n").replace("\r", "\n")


def frontmatter_parts(text):
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\n") != "---":
        return None, text
    for index, line in enumerate(lines[1:], 1):
        if line.rstrip("\n") == "---":
            return "".join(lines[1:index]), "".join(lines[index + 1 :])
    raise ValueError("frontmatter starts but has no closing --- line")


def exact_body_after_frontmatter(text):
    if text.startswith("\ufeff"):
        raise ValueError("UTF-8 BOM is not allowed in a canonical source")
    start = re.match(r"\A---(?:\r\n|\n)", text)
    if not start:
        return None
    closing = re.search(r"(?m)^---(?:\r\n|\n|\Z)", text[start.end() :])
    if not closing:
        raise ValueError("frontmatter starts but has no closing --- line")
    return text[start.end() + closing.end() :]


def markdown_lines(text, label):
    lines = []
    fence_char = None
    fence_length = 0
    for raw in text.splitlines(keepends=True):
        line = raw.rstrip("\r\n")
        if fence_char is None:
            opening = FENCE_OPEN_RE.match(line)
            if opening:
                marker = opening.group(1)
                fence_char = marker[0]
                fence_length = len(marker)
                continue
            lines.append((raw, False))
            continue

        closing = FENCE_CLOSE_RE.fullmatch(line)
        if closing:
            marker = closing.group(1)
            if marker[0] == fence_char and len(marker) >= fence_length:
                fence_char = None
                fence_length = 0
                continue
        lines.append((raw, True))

    if fence_char is not None:
        raise ValueError(f"{label} contains an unclosed fenced block")
    return lines


def without_inline_code(text):
    output = []
    index = 0
    while index < len(text):
        if text[index] != "`":
            output.append(text[index])
            index += 1
            continue
        end = index + 1
        while end < len(text) and text[end] == "`":
            end += 1
        marker = text[index:end]
        closing = text.find(marker, end)
        while closing >= 0 and (
            (closing > 0 and text[closing - 1] == "`")
            or (closing + len(marker) < len(text) and text[closing + len(marker)] == "`")
        ):
            closing = text.find(marker, closing + len(marker))
        if closing < 0:
            output.append(marker)
            index = end
            continue
        span_end = closing + len(marker)
        output.append("".join("\n" if char == "\n" else " " for char in text[index:span_end]))
        index = span_end
    return "".join(output)


def reject_slots(text, label):
    searchable = "".join(raw for raw, fenced in markdown_lines(text, label) if not fenced)
    searchable = without_inline_code(searchable)

    match = BRACE_SLOT_RE.search(searchable)
    if match:
        raise ValueError(f"{label} contains unfilled template slot {match.group(0)!r}")


def content_lines(text, include_fenced=True, label="artifact"):
    lines = []
    for raw, fenced in markdown_lines(text, label):
        line = raw.strip()
        if not line or line == "---" or HEADING_RE.match(line):
            continue
        if fenced and not include_fenced:
            continue
        lines.append(line)
    return lines


def instruction_lines(text, label):
    out = set()
    for line in content_lines(text, include_fenced=False, label=label):
        normalized = re.sub(r"^(?:[-*+]\s+|\d+[.)]\s+)", "", line).strip()
        if len(normalized) >= 3:
            out.add(normalized)
    return out


def validate_plain(path, kind, require_content=True):
    text = logical_text(read_text(path), path)
    frontmatter, _ = frontmatter_parts(text)
    if frontmatter is not None:
        raise ValueError(f"{kind} must not contain frontmatter: {path}")
    reject_slots(text, kind)
    if require_content and not content_lines(text, label=kind):
        raise ValueError(f"{kind} has no content: {path}")
    return text


def parse_simple_frontmatter(block, path):
    values = {}
    for number, raw in enumerate(block.splitlines(), 1):
        if not raw.strip():
            continue
        match = re.fullmatch(r"([a-z][a-z0-9-]*):\s*(.*)", raw)
        if not match:
            raise ValueError(f"unsupported frontmatter syntax at {path}:{number}")
        key, value = match.groups()
        if key in values:
            raise ValueError(f"duplicate frontmatter key {key!r} in {path}")
        values[key] = value.strip()
    return values


def validate_output_style(path):
    text = logical_text(read_text(path), path)
    frontmatter, body = frontmatter_parts(text)
    if frontmatter is None:
        raise ValueError(f"output style requires frontmatter: {path}")
    values = parse_simple_frontmatter(frontmatter, path)
    allowed = {"name", "description", "keep-coding-instructions"}
    unknown = sorted(set(values) - allowed)
    if unknown:
        raise ValueError(f"unsupported output-style keys in {path}: {', '.join(unknown)}")
    if not values.get("description"):
        raise ValueError(f"output style requires a non-empty description: {path}")
    if values.get("keep-coding-instructions") != "true":
        raise ValueError(
            f"output style requires boolean keep-coding-instructions: true: {path}"
        )
    reject_slots(text, "output style")
    if not content_lines(body, label="output style"):
        raise ValueError(f"output style has no instruction body: {path}")
    return text, body


def validate_settings(path):
    def no_duplicate_keys(pairs):
        value = {}
        for key, item in pairs:
            if key in value:
                raise ValueError(f"duplicate JSON key {key!r} in {path}")
            value[key] = item
        return value

    def no_constants(value):
        raise ValueError(f"non-standard JSON value {value!r} in {path}")

    try:
        value = json.loads(
            read_text(path),
            object_pairs_hook=no_duplicate_keys,
            parse_constant=no_constants,
        )
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON in {path}: {exc.msg} at line {exc.lineno}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"settings root must be an object: {path}")
    if "outputStyle" in value and (
        not isinstance(value["outputStyle"], str) or not value["outputStyle"].strip()
    ):
        raise ValueError(f"outputStyle must be a non-empty string: {path}")
    if "attribution" in value:
        attribution = value["attribution"]
        if not isinstance(attribution, dict):
            raise ValueError(f"attribution must be an object: {path}")
        for key in ("commit", "pr"):
            if key in attribution and not isinstance(attribution[key], str):
                raise ValueError(f"attribution.{key} must be a string: {path}")
    return value


def canonical_source_body(path):
    raw = read_text(path)
    logical = logical_text(raw, path)
    frontmatter, _ = frontmatter_parts(logical)
    if frontmatter is None:
        validate_plain(path, "canonical source")
        return raw
    validate_output_style(path)
    return exact_body_after_frontmatter(raw)


def trim_blank_edges(text):
    lines = text.split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def derived_text(source_paths):
    parts = []
    for path in source_paths:
        body = canonical_source_body(path)
        parts.append(trim_blank_edges(logical_text(body, path)))
    return "\n\n".join(parts) + "\n"


def check_derived(append_path, source_paths):
    append_text = read_text(append_path)
    expected = derived_text(source_paths)
    if append_text != expected:
        raise ValueError(
            f"derived append file differs from canonical sources: {append_path}"
        )


def existing_body(path):
    text = logical_text(read_text(path), path)
    _, body = frontmatter_parts(text)
    return body


def check_duplicates(named_texts):
    seen = {}
    duplicates = []
    for label, text in named_texts:
        for line in sorted(instruction_lines(text, label)):
            previous = seen.get(line)
            if previous and previous != label:
                duplicates.append((line, previous, label))
            else:
                seen[line] = label
    if duplicates:
        details = "; ".join(
            f"{line!r} in {left} and {right}" for line, left, right in duplicates
        )
        raise ValueError(f"exact duplicate instruction lines: {details}")


def parse_style_expectations(items, settings_paths):
    expected = {}
    available = {str(Path(path).resolve()) for path in settings_paths}
    for item in items:
        if "=" not in item:
            raise ValueError("--expect-output-style must be FILE=NAME")
        path, name = item.split("=", 1)
        resolved = str(Path(path).resolve())
        if resolved not in available:
            raise ValueError(f"expected outputStyle path is not a --settings file: {path}")
        if not name.strip():
            raise ValueError("--expect-output-style requires a non-empty NAME")
        if resolved in expected:
            raise ValueError(f"duplicate outputStyle expectation for {path}")
        expected[resolved] = name
    return expected


def parse_attribution_expectations(items, settings_paths):
    available = {str(Path(path).resolve()) for path in settings_paths}
    expected = set()
    for path in items:
        resolved = str(Path(path).resolve())
        if resolved not in available:
            raise ValueError(f"attribution expectation path is not a --settings file: {path}")
        if resolved in expected:
            raise ValueError(f"duplicate attribution expectation for {path}")
        expected.add(resolved)
    return expected


def build_parser():
    p = JsonArgumentParser(description=__doc__)
    p.add_argument("--core", help="user-level core rules file")
    p.add_argument("--delta", help="project delta rules file")
    p.add_argument("--rules", action="append", default=[], help="single-layer rules file")
    p.add_argument("--output-style", action="append", default=[], help="output-style file")
    p.add_argument("--append", help="portable append file")
    p.add_argument(
        "--derived-from",
        action="append",
        default=[],
        help="canonical source for --append, in concatenation order",
    )
    p.add_argument("--settings", action="append", default=[], help="settings JSON file")
    p.add_argument(
        "--expect-output-style",
        action="append",
        default=[],
        metavar="FILE=NAME",
        help="require one settings file to contain an outputStyle value",
    )
    p.add_argument(
        "--expect-attribution-off",
        action="append",
        default=[],
        metavar="FILE",
        help="require one settings file to disable commit and PR attribution",
    )
    p.add_argument(
        "--existing",
        action="append",
        default=[],
        help="existing instruction file to include in exact-duplicate checks",
    )
    return p


def fail(message):
    print(json.dumps({"error": str(message), "status": "fail"}, sort_keys=True))


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    artifact_count = sum(
        bool(value)
        for value in (
            args.core,
            args.delta,
            args.rules,
            args.output_style,
            args.append,
            args.settings,
        )
    )
    if not artifact_count:
        parser.error("provide at least one artifact")
    if bool(args.append) != bool(args.derived_from):
        parser.error("--append and one or more --derived-from values must be supplied together")
    if (args.expect_output_style or args.expect_attribution_off) and not args.settings:
        parser.error("settings expectations require --settings")

    checked = []
    ownership_texts = []
    try:
        style_expectations = parse_style_expectations(
            args.expect_output_style, args.settings
        )
        attribution_expectations = parse_attribution_expectations(
            args.expect_attribution_off, args.settings
        )
        if args.core:
            text = validate_plain(args.core, "core rules")
            ownership_texts.append((f"core:{args.core}", text))
            checked.append(f"core:{args.core}")
        if args.delta:
            text = validate_plain(args.delta, "project delta")
            ownership_texts.append((f"delta:{args.delta}", text))
            checked.append(f"delta:{args.delta}")
        for path in args.rules:
            text = validate_plain(path, "rules file")
            ownership_texts.append((f"rules:{path}", text))
            checked.append(f"rules:{path}")
        for path in args.output_style:
            _, body = validate_output_style(path)
            ownership_texts.append((f"output-style:{path}", body))
            checked.append(f"output-style:{path}")
        if args.append:
            validate_plain(args.append, "append file")
            check_derived(args.append, args.derived_from)
            checked.append(f"append:{args.append}")
            checked.extend(f"derived-from:{path}" for path in args.derived_from)
        for path in args.settings:
            value = validate_settings(path)
            resolved = str(Path(path).resolve())
            if resolved in style_expectations:
                expected = style_expectations[resolved]
                if value.get("outputStyle") != expected:
                    raise ValueError(
                        f"outputStyle must equal {expected!r} in {path}; "
                        f"found {value.get('outputStyle')!r}"
                    )
            if resolved in attribution_expectations:
                expected = {"commit": "", "pr": ""}
                if value.get("attribution") != expected:
                    raise ValueError(f"attribution must equal {expected!r} in {path}")
            checked.append(f"settings:{path}")
        for path in args.existing:
            ownership_texts.append((f"existing:{path}", existing_body(path)))
            checked.append(f"existing:{path}")
        if len(ownership_texts) > 1:
            check_duplicates(ownership_texts)
    except ValueError as exc:
        fail(exc)
        return 1

    print(
        json.dumps(
            {
                "checked": checked,
                "limitations": [
                    "exact duplicate checks ignore headings and fenced examples",
                    "unfilled-slot checks cover {{...}} outside fenced and inline code",
                    "semantic paraphrases require inventory and human judgment",
                ],
                "status": "pass",
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
